# Generated by Django 3.2.4 on 2021-06-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodorder', '0002_alter_customer_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='social_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
